CREATE TABLE IF NOT EXISTS sch_autenticacao.tb_acesso_perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_acesso BIGINT NOT NULL,
    id_perfil BIGINT NULL,
    CONSTRAINT perfil_acao_unique UNIQUE (id_perfil, id_acesso),
    CONSTRAINT tb_perfil_acesso_fk FOREIGN KEY (id_perfil) REFERENCES sch_autenticacao.tb_perfil(id),
    CONSTRAINT tb_acesso_perfil_fk FOREIGN KEY (id_acesso) REFERENCES sch_autenticacao.tb_acesso(id)
);