
CREATE TABLE IF NOT EXISTS sch_autenticacao.tb_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha VARCHAR(256) NOT NULL,
    id_perfil BIGINT NOT NULL,
    status BOOL NULL,
    CONSTRAINT usuario_unique_email UNIQUE (email),
    CONSTRAINT tb_usuario_tb_perfil_fk FOREIGN KEY (id_perfil) REFERENCES sch_autenticacao.tb_perfil(id)
);

