CREATE SCHEMA IF NOT EXISTS sch_autenticacao;

CREATE TABLE IF NOT EXISTS sch_autenticacao.tb_perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    status BOOL NULL,
    CONSTRAINT perfil_unique_nome UNIQUE (nome)
);

INSERT INTO sch_autenticacao.tb_perfil (nome, descricao, status)
VALUES ('ADM', 'Administrador', true);

INSERT INTO sch_autenticacao.tb_perfil (nome, descricao, status)
VALUES ('USUARIO', 'Usuário', true);

